/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TitleType = IDL.Variant({
  'movie' : IDL.Null,
  'series' : IDL.Null,
});
export const TitleInput = IDL.Record({
  'title' : IDL.Text,
  'video' : ExternalBlob,
  'description' : IDL.Text,
  'titleType' : TitleType,
  'coverImage' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Title = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'ratingCount' : IDL.Nat,
  'video' : ExternalBlob,
  'description' : IDL.Text,
  'titleType' : TitleType,
  'averageRating' : IDL.Float64,
  'coverImage' : ExternalBlob,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTitle' : IDL.Func([TitleInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTitle' : IDL.Func([IDL.Nat], [], []),
  'getAllTitles' : IDL.Func([], [IDL.Vec(Title)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTitleById' : IDL.Func([IDL.Nat], [Title], ['query']),
  'getTitleRatings' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({ 'ratingCount' : IDL.Nat, 'averageRating' : IDL.Float64 })
        ),
      ],
      ['query'],
    ),
  'getTitlesByType' : IDL.Func([TitleType], [IDL.Vec(Title)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateTitle' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTitles' : IDL.Func([IDL.Text], [IDL.Vec(Title)], ['query']),
  'updateTitle' : IDL.Func([IDL.Nat, TitleInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TitleType = IDL.Variant({ 'movie' : IDL.Null, 'series' : IDL.Null });
  const TitleInput = IDL.Record({
    'title' : IDL.Text,
    'video' : ExternalBlob,
    'description' : IDL.Text,
    'titleType' : TitleType,
    'coverImage' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Title = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'ratingCount' : IDL.Nat,
    'video' : ExternalBlob,
    'description' : IDL.Text,
    'titleType' : TitleType,
    'averageRating' : IDL.Float64,
    'coverImage' : ExternalBlob,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTitle' : IDL.Func([TitleInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTitle' : IDL.Func([IDL.Nat], [], []),
    'getAllTitles' : IDL.Func([], [IDL.Vec(Title)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTitleById' : IDL.Func([IDL.Nat], [Title], ['query']),
    'getTitleRatings' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'ratingCount' : IDL.Nat,
              'averageRating' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getTitlesByType' : IDL.Func([TitleType], [IDL.Vec(Title)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateTitle' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTitles' : IDL.Func([IDL.Text], [IDL.Vec(Title)], ['query']),
    'updateTitle' : IDL.Func([IDL.Nat, TitleInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };